/* eslint-disable */
/**
 * AUTO-GENERATED by bevy-react bridge-codegen — do not edit by hand.
 * Regenerate: `./scripts/generate-bridge-types.sh`
 */
export type PlayerStats = { hp: number, max_hp: number, score: number, };
