/* eslint-disable */
/**
 * AUTO-GENERATED by bevy-react bridge-codegen — do not edit by hand.
 * Regenerate: `./scripts/generate-bridge-types.sh`
 */
export const PLAYER_STATS_KEYS = ["hp", "max_hp", "score"] as const;
