//! TypeScript codegen helpers for the React bridge.
//!
//! Enabled with the `bridge-codegen` feature (`ts-rs`). Apps annotate
//! serializable resources with `#[derive(ts_rs::TS)]`, list
//! [`BridgeCommandMeta`] for registered `callNative` handlers, then call
//! [`write_bridge_typescript`] (or assert with [`assert_bridge_typescript_fresh`]).
//!
//! See `docs/BRIDGE.md` and `scripts/generate-bridge-types.sh`.

use std::fs;
use std::path::{Path, PathBuf};

use ts_rs::{Config, TS};

/// Metadata for one `ReactBridge::register` command, used to emit typed wrappers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BridgeCommandMeta {
    /// Rust / JS command name passed to `register` / `callNative` (e.g. `"add_score"`).
    pub name: &'static str,
    /// TypeScript identifier for the wrapper function (e.g. `"addScore"`).
    pub ts_fn: &'static str,
    /// TypeScript type of the optional args payload (e.g. `"number"`, `"void"`).
    pub args_ts: &'static str,
    /// TypeScript type of the Promise result (e.g. `"{ score: number }"`).
    pub result_ts: &'static str,
}

/// Header prepended to every generated file.
pub const GENERATED_HEADER: &str = "\
/* eslint-disable */
/**
 * AUTO-GENERATED by bevy-react bridge-codegen — do not edit by hand.
 * Regenerate: `./scripts/generate-bridge-types.sh`
 */
";

/// Render typed `callNative` wrappers from command metadata.
pub fn emit_command_wrappers(commands: &[BridgeCommandMeta]) -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str("import { callNative } from \"bevy-react\";\n\n");

    for cmd in commands {
        let result_alias = format!("{}Result", to_pascal_case(cmd.ts_fn));
        out.push_str(&format!(
            "export type {result_alias} = {};\n",
            cmd.result_ts
        ));

        if cmd.args_ts == "void" || cmd.args_ts.is_empty() {
            out.push_str(&format!(
                "export function {}(): Promise<{result_alias}> {{\n  return callNative<{result_alias}>(\"{}\");\n}}\n\n",
                cmd.ts_fn, cmd.name
            ));
        } else {
            out.push_str(&format!(
                "export function {}(args: {}): Promise<{result_alias}> {{\n  return callNative<{result_alias}>(\"{}\", args);\n}}\n\n",
                cmd.ts_fn, cmd.args_ts, cmd.name
            ));
        }
    }

    out
}

/// Emit a single type declaration file from a `ts-rs` type (`T::decl`).
pub fn emit_type_decl<T: TS>() -> String {
    let cfg = Config::default();
    let mut decl = T::decl(&cfg);
    // ts-rs emits `type Name = …;` without `export` — add it for ES modules.
    if decl.starts_with("type ") {
        decl = format!("export {decl}");
    }
    let mut out = String::from(GENERATED_HEADER);
    out.push_str(&decl);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Emit `export const FOO_KEYS = [...]` for JSON object keys (serde field order).
pub fn emit_object_keys_const(const_name: &str, keys: &[&str]) -> String {
    let mut out = String::from(GENERATED_HEADER);
    let quoted: Vec<String> = keys.iter().map(|k| format!("\"{k}\"")).collect();
    out.push_str(&format!(
        "export const {const_name} = [{}] as const;\n",
        quoted.join(", ")
    ));
    out
}

/// Bundle of generated TypeScript files keyed by relative path under `out_dir`.
#[derive(Debug, Clone)]
pub struct GeneratedBridgeTs {
    pub files: Vec<(String, String)>,
}

impl GeneratedBridgeTs {
    pub fn new() -> Self {
        Self { files: Vec::new() }
    }

    pub fn push(&mut self, relative: impl Into<String>, contents: impl Into<String>) {
        self.files.push((relative.into(), contents.into()));
    }

    pub fn with_type<T: TS>(mut self, relative: impl Into<String>) -> Self {
        self.push(relative, emit_type_decl::<T>());
        self
    }

    pub fn with_commands(
        mut self,
        relative: impl Into<String>,
        commands: &[BridgeCommandMeta],
    ) -> Self {
        self.push(relative, emit_command_wrappers(commands));
        self
    }

    pub fn with_keys(
        mut self,
        relative: impl Into<String>,
        const_name: &str,
        keys: &[&str],
    ) -> Self {
        self.push(relative, emit_object_keys_const(const_name, keys));
        self
    }

    pub fn with_barrel(
        mut self,
        relative: impl Into<String>,
        reexports: &[&str],
    ) -> Self {
        let mut out = String::from(GENERATED_HEADER);
        for path in reexports {
            let module = path.trim_end_matches(".ts");
            out.push_str(&format!("export * from \"./{module}\";\n"));
        }
        self.push(relative, out);
        self
    }
}

impl Default for GeneratedBridgeTs {
    fn default() -> Self {
        Self::new()
    }
}

/// Write all generated files under `out_dir`, creating parent dirs as needed.
pub fn write_bridge_typescript(out_dir: &Path, bundle: &GeneratedBridgeTs) -> std::io::Result<()> {
    for (rel, contents) in &bundle.files {
        let path = out_dir.join(rel);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&path, contents)?;
    }
    Ok(())
}

/// Compare on-disk files to `bundle`; return Ok(()) when identical.
///
/// On mismatch, returns an error string listing diverging paths. When
/// `update` is true, writes the bundle first (always Ok).
pub fn sync_bridge_typescript(
    out_dir: &Path,
    bundle: &GeneratedBridgeTs,
    update: bool,
) -> Result<(), String> {
    if update {
        write_bridge_typescript(out_dir, bundle).map_err(|e| e.to_string())?;
        return Ok(());
    }

    let mut stale = Vec::new();
    for (rel, expected) in &bundle.files {
        let path = out_dir.join(rel);
        match fs::read_to_string(&path) {
            Ok(actual) if actual == *expected => {}
            Ok(_) => stale.push(format!("{} (content differs)", path.display())),
            Err(_) => stale.push(format!("{} (missing)", path.display())),
        }
    }

    if stale.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "Generated bridge TypeScript is stale:\n  {}\nRun: ./scripts/generate-bridge-types.sh",
            stale.join("\n  ")
        ))
    }
}

/// Convenience for `#[test]`: fail when generated output is stale unless
/// `UPDATE_BRIDGE_TYPES=1` (then rewrite).
pub fn assert_bridge_typescript_fresh(out_dir: &Path, bundle: &GeneratedBridgeTs) {
    let update = std::env::var("UPDATE_BRIDGE_TYPES")
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
        .unwrap_or(false);
    if let Err(msg) = sync_bridge_typescript(out_dir, bundle, update) {
        panic!("{msg}");
    }
}

/// Resolve `examples/hud/ui/src/generated` from this crate's manifest (plugin/).
pub fn default_hud_generated_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../examples/hud/ui/src/generated")
}

fn to_pascal_case(camel: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for c in camel.chars() {
        if c == '_' || c == '-' {
            upper = true;
            continue;
        }
        if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_command_wrappers_void_and_args() {
        let ts = emit_command_wrappers(&[
            BridgeCommandMeta {
                name: "add_score",
                ts_fn: "addScore",
                args_ts: "number",
                result_ts: "{ score: number }",
            },
            BridgeCommandMeta {
                name: "heal",
                ts_fn: "heal",
                args_ts: "void",
                result_ts: "{ hp: number }",
            },
        ]);
        assert!(ts.contains("export function addScore(args: number)"));
        assert!(ts.contains("callNative<AddScoreResult>(\"add_score\", args)"));
        assert!(ts.contains("export function heal(): Promise<HealResult>"));
        assert!(ts.contains("callNative<HealResult>(\"heal\")"));
    }

    #[test]
    fn pascal_case_helpers() {
        assert_eq!(to_pascal_case("addScore"), "AddScore");
        assert_eq!(to_pascal_case("heal"), "Heal");
    }
}
